package com.ughcentral.fruitful;

public enum Keyword {
    NO_BOOM, NO_DECAY, NO_WATER, NO_BREAK, SECURE, NO_OVERRIDE, BURNABLE, SHEARABLE, DISABLED, BURNING, RAINBOW, SHEARED, ELECTRIC, SADDLED, ANGRY;
}
